---

# tasks file for asravankumar.python_virtual_envs


- name: Install Direnv
  apt: name={{ item }} state=installed
  become: True
  with_items:
    - direnv

- name: Activate Pyenv VirtualEnv
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'eval "$(pyenv virtualenv-init -)"'

- name: Activate direnv
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'eval "$(direnv hook bash)"'

- name: Create direnv config directory
  file: path=/home/ubuntu/.config/direnv state=directory

- name: Copy Direnv config
  copy:
    src=direnvrc
    dest=/home/ubuntu/.config/direnv/
